### ISSUE TITLE
Paradigma Mismatch: Achseninversion wirkt sich nicht auf den Wurf aus

### ISSUE THREAD

**Issue by EJochmann** [JesseRed/VRMotorLearnCK#11]
z.B. bei Negativierung der y-Achse (vorne/hinten) muss die Hand für die gewollte Darstellung der Handbewegung invers bewegt werden. Wenn der Ball aber geworfen wird, muss die Hand normal von hinten nach vorne bewegt werden, um den Ball nach vorne zu beschleunigen. Die inverse Bewegung (von vorne nach hinten) führt zu einem Wurf hinter sich.

Gibt es ein gesondertes Skript, wie die Handbewegung auf den Ball wirkt? Dann müsste dieses auch angepasst werden bei Achseninversion. Aktuell kann man die Zielscheibe sehr gut treffen wenn man einmal raus hat, dass man die Hand nur in die Mitte bringen muss und dann einfach normal wirft.

**Comment by JesseRed** [comment]
very difficult problem
hat alle Achsen betroffen ...
solved
