### ISSUE TITLE
Bitte vor 14.4.: Reihenfolge der Paradigmen

### ISSUE THREAD

**Issue by EJochmann** [JesseRed/VRMotorLearnCK#12]
Bitte Anpassung an Randomisierungssoftware, damit es keine Fehlverteilungen gibt:

1 - Mismatch Learning
2 - Error-based Learning
3 - Errorless Learning

Hab es leider selber nicht geschafft, das Programm hing nach meinen Versuchen immer.

**Comment by JesseRed** [comment]
solved
