### ISSUE TITLE
Projekt Kühnhold - ClinicalVR (Wurfspiel für Stroke-Patienten)

### ISSUE THREAD

**Issue by EJochmann** [JesseRed/VRMotorLearnCK#19]
- innere Ringe auf Zielscheibe ergänzen (z.B. 2 weitere blaue Ringe (wie Außenring) + Mittelpunkt) 
- in .json file Möglichkeit "innere Ringe" ein/aus
- Paradigma 4 ergänzen (analog 3, zusätzlich "innere Ringe" "ein")
(Ziel: Leistungserhebung in Errorless Paradigma mittels Vergleich von Durchschnittsabstand der Treffer vom Mittelpunkt vor und nach dem Training in Error-based Paradigma)

**Comment by JesseRed** [comment]
solved ... genau wie oben beschrieben
