### ISSUE TITLE
Treffererkennung

### ISSUE THREAD

**Issue by Tarlo95** [JesseRed/VRMotorLearnCK#25]
1. Trefferquote als Ingame Feld (zum testen)
2. Überprüfen ob die Treffererkennung richtig ist. Oft bin ich zu mind. 80% der letzten Sekunden auf dem Ball und er wird trotzdem langsamer obwohl ja nur 50% trefferquote erreicht werden soll

**Comment by JesseRed** [comment]
es gibt nun die TR Anzeige ... diese zeigt die aktuelle HitRate an
    private int list_length = 120;

    public void add_punkte(float dist, float ball_size, float t){
        fingerBallDist.Add(dist);
        timepoint.Add(t);
        if (dist<ball_size/2){treffer.Add(1.0f);}else{treffer.Add(0.0f);}
        treffersum += treffer[treffer.Count-1];
        if (fingerBallDist.Count>list_length){
            treffersum -= treffer[0];
            fingerBallDist.RemoveAt(0);
            timepoint.RemoveAt(0);
            treffer.RemoveAt(0);
        }      

Der algorithmus ist aktuell so, dass nur 2 Sekunden lang die Hits aufgezeichnet werden. d.h. HitRate ist die der letzten 2 Sekunden
kann man aendern .... vielleicht auch noch ins parameterfile?

**Comment by JesseRed** [comment]
es gibt nun im Parameterfile den Parameter 
    "adapt_veloc_in_trial_based_on_last_framenum" : 120,
die Zahl sind die Anzahl der Frames ueber die Aufgezeichnet wird
