### ISSUE TITLE
Anzeigetafel Ballfolgeparadigma

### ISSUE THREAD

**Issue by EJochmann** [JesseRed/VRMotorLearnCK#26]
Anzeigetafel ändert sich nach etwa 2 Sekunden von initialer Aufforderung "!!Bitte versuchen sie immer mit dem Zeigefinger in Kontakt mit dem roten Ball zu bleiben. Der BAll wird sich bewegen sobald sie ihn beruehren" zu: "cloneplayBall Versuchen sie mit dem Zeigefinger immer im Kontakt mit dem Ball zu bleiben"

**Bitte ändern in dauerhaft:**
Bitte versuchen Sie, immer mit dem Zeigefinger in Kontakt mit dem roten Ball zu bleiben. Der Ball wird sich bewegen, sobald Sie ihn berühren.

**Comment by JesseRed** [comment]
erledigt
