### ISSUE TITLE
Zeit zwischen Bällen einstellbar (Ballfolgeparadigma)

### ISSUE THREAD

**Issue by EJochmann** [JesseRed/VRMotorLearnCK#27]
Einstellmöglichkeit für Zeit x zwischen Ende des vorherigen Balls und Erscheinen des nächsten Balls

**Comment by JesseRed** [comment]
Es gibt nun die Option "no_ball_duration" im Parameterfile.
Hab ich schon fuer Paradigm3-5 eingetragen
Die Zahl die da steht wird runter gezaehlt und auf der Anzeigetafel angezeigt
